#RENAME this file to config.yaml if program is being run locally.
canvas:
        request_parameters:     <Enter_Additional_Parameters>
        bearer_token:           <Enter_Canvas_Token_Here>
        course_id:              <Enter_Course_ID_Here>

google_sheets:
        spreadsheet_ID:         <Enter_Spreadsheet_ID_Here>
        sheet_range:            <Enter_Sheet_Range_Here>
